# Puerto de escucha
server.port=8080

# Configuracion de MariaDB
# Puerto externo 4306 segun enunciado
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.url=jdbc:mariadb://${DB_HOST:localhost}:${DB_PORT:4306}/${DB_NAME:hogwarts_xxx}
spring.datasource.username=${DB_USER:aaee_xxx}
spring.datasource.password=${DB_PASSWORD:1234}

# Pool de conexiones Hikari
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2